### ISSUE TITLE
[FR-1] Login/Sign Up Menu

### ISSUE THREAD

**Issue by gi5229** [WSU-4110/DAIRemote#1]
### Goal

A simple screen for users to Login or signup.

### Description

A minimal page that will prompt the user to either choose to sign in as an existing user or to create a new account. 

### Stakeholders

User

### Date

9/18/2024

### Version

0.1

### Origin

Group Meeting #1

### Priority of the proposed feature

Must have

**Comment by mehad123** [comment]
User is not part of our group, therefore issue ignored.
